### PR TITLE
Fix copyright in README

### LINKED ISSUE #75: Correct copyright notices to reflect Copyright OpenSearch Contributors
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

### PR DESCRIPTION
**Pull request by jmazanec15**
Signed-off-by: John Mazanec <jmazane@amazon.com>

### Description
Modify Copyright Description in README. I could not find other instances outside of the README. 

Related: https://github.com/opensearch-project/.github/pull/24
 
### Issues Resolved
#75 
 
### Check List
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Review by VijayanB — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
Your NOTICE.txt contains k-nn, which I think should be removed and replaced with just OpenSearch Contributors. I believe you should also remove ODFE references.

**Comment by jmazanec15** [comment]
@dblock makes sense, will update. 

Which ODFE references are you referring to? I see the one in the NOTICE.txt, but there are also the licenses in the code (I assume this is not what you are talking about).

**Comment by dblock** [comment]
> @dblock makes sense, will update.
> 
> Which ODFE references are you referring to? I see the one in the NOTICE.txt, but there are also the licenses in the code (I assume this is not what you are talking about).

I only meant `OpenDistroForElasticsearch` in the NOTICE

**Review by dblock — APPROVED** [review]

**Pull request merged**
