### PR TITLE
Update bwc workflow to include 2.12.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ryanbogan**
### Description
Updates the bwc workflow to pull from 2.12.0-SNAPSHOT.  This fixes the failing rolling upgrade bwc tests on CI.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by heemin32 — APPROVED** [review]

**Comment by VijayanB** [comment]
@ryanbogan Did you make this change? i think we have command to automate this process? i may be wrong too @naveentatikonda do you aware of this?

**Comment by ryanbogan** [comment]
> @ryanbogan Did you make this change manually? i think we have command to automate this process? i may be wrong too @naveentatikonda do you aware of this?

Yeah, I raised the PR manually.  The only automated PR's I've seen are for 2.x, not for main.

**Comment by VijayanB** [comment]
> > @ryanbogan Did you make this change manually? i think we have command to automate this process? i may be wrong too @naveentatikonda do you aware of this?
> 
> Yeah, I raised the PR manually. The only automated PR's I've seen are for 2.x, not for main.

Got it. Can you create an issue to automate on main too?

**Review by VijayanB — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@VijayanB @ryanbogan We have the logic to update the bwc version in main branch as well. But, as of now it gets triggered when the OS version bump PR is created. Need to figure out a way to update bwc version on main when it is updated on 2.x branch.

**Pull request merged**
