### PR TITLE
Add CI to run every night

### PR DESCRIPTION
**Pull request by VijayanB**
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>

### Description
Github doesn't support non-standard like @daily, we have to use
standard cron syntax.
  
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VijayanB** [comment]
> Should this be backported to 1.x as well @VijayanB ?

What is the difference between 1.x and main?

**Comment by jmazanec15** [comment]
@VijayanB we are going to start developing for 2.0 on main and backport everything for 1.x to 1.x branch.

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by VijayanB** [comment]
> 

Nice, i would assume when we do that, we will reset branch 1.x to main and start new development going forward.

**Review by jmazanec15 — APPROVED** [review]

**Comment by dblock** [comment]
Are these different runs from push and PRs? Why is it necessary to also run on cron?

**Comment by vamshin** [comment]
@dblock We have a goal to run nightly tests to ensure stable builds. This PR is in alignment to that goal.

**Pull request merged**
