### PR TITLE
Increment version to 1.2.2.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Increment version to 1.2.2.

### Check List

- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jmazanec15 — DISMISSED** [review]

**Review by naveentatikonda — APPROVED** [review]

**Comment by dblock** [comment]
```
329 tests completed, 2 failed
Tests with failures:
 - org.opensearch.knn.plugin.transport.RemoveModelFromCacheTransportActionTests.testNodeOperation_modelInCache
 - org.opensearch.knn.plugin.transport.RemoveModelFromCacheTransportActionTests.testNodeOperation_modelNotInCache
```

**Comment by jmazanec15** [comment]
Tried to repro locally but could not. 

The test failure that is relevant is testNodeOperation_modelInCache. The other test carries state from this test (which needs to be fixed) and that causes the failure. I believe if testNodeOperation_modelInCache succeeds then the other one will as well.

I see someone kicked off another run. I am going to see what happens and continue looking into why testNodeOperation_modelInCache may have failed.

**Comment by vamshin** [comment]
> Tried to repro locally but could not.
> 
> The test failure that is relevant is testNodeOperation_modelInCache. The other test carries state from this test (which needs to be fixed) and that causes the failure. I believe if testNodeOperation_modelInCache succeeds then the other one will as well.
> 
> I see someone kicked off another run. I am going to see what happens and continue looking into why testNodeOperation_modelInCache may have failed.

@jmazanec15 I kicked another run to see if the issue is transient

**Comment by jmazanec15** [comment]
These 2 tests appear to be flaky. From output:
```
  1> [2021-12-15T11:01:35,225][INFO ][o.o.k.p.t.RemoveModelFromCacheTransportActionTests] [testNodeOperation_modelInCache] before test
  1> [2021-12-15T11:01:35,231][INFO ][o.o.k.i.ModelCache       ] [testNodeOperation_modelInCache] [KNN] Model Cache evicted. Key test-model-id, Reason: EXPLICIT
  1> [2021-12-15T11:01:35,234][INFO ][o.o.k.p.t.RemoveModelFromCacheTransportActionTests] [testNodeOperation_modelInCache] after test
```

Model gets evicted. But cache may not update in time for assert. 

Given that I am unable to reproduce failure locally, I think these cases can be commented out @dblock and marked as flaky.

**Pull request closed without merging**
