### PR TITLE
Refactor xcontent package name from common to core

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Refactor package common to core for XContent as upstream made these changes.
OpenSearch PR: https://github.com/opensearch-project/OpenSearch/pull/5902.

### Check List
- [x] All tests pass
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by naveentatikonda** [comment]
The failing BWC Tests is not related to the changes in this PR. Some BWC tests with BWC version as 2.6.0-SNAPSHOT is failing because we don't have k-NN plugin in the artifact.

**Comment by jmazanec15** [comment]
> The failing BWC Tests is not related to the changes in this PR. Some BWC tests with BWC version as 2.6.0-SNAPSHOT is failing because we don't have k-NN plugin in the artifact.

Why dont we have k-NN plugin in the artifact? I believe it had been in previous 2.6.0-SNAPSHOT artifacts.

**Comment by naveentatikonda** [comment]
> > The failing BWC Tests is not related to the changes in this PR. Some BWC tests with BWC version as 2.6.0-SNAPSHOT is failing because we don't have k-NN plugin in the artifact.
> 
> Why dont we have k-NN plugin in the artifact? I believe it had been in previous 2.6.0-SNAPSHOT artifacts.

Yes, it was there in the past. But, yesterday when the check failed, I saw the zip and there is only 'job-scheduler' plugin in it. Not sure why the build team removed, I thought they were doing some testing

**Comment by naveentatikonda** [comment]
Closing this PR as these changes are already addressed in this PR
https://github.com/opensearch-project/k-NN/pull/781

**Pull request closed without merging**
