### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/k-NN/pull/1
 
### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/k-NN/issues/433
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Renaming task to `updateVersion` following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32

**Comment by prudhvigodithi** [comment]
Renaming to task `updateVersion` following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Review by jmazanec15 — DISMISSED** [review]

**Comment by jmazanec15** [comment]
@prudhvigodithi One other place that version needs to be updated: https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/backwards_compatibility_tests_workflow.yml#L18, https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/backwards_compatibility_tests_workflow.yml#L50.

Can it be added here as well?

**Comment by prudhvigodithi** [comment]
Hey @jmazanec15 I have included `.github/workflows/backwards_compatibility_tests_workflow.yml`  and tested executing the task 
`./gradlew updateVersion -DnewVersion=2.2.0-SNAPSHOT`

```
diff --git a/.github/workflows/backwards_compatibility_tests_workflow.yml b/.github/workflows/backwards_compatibility_tests_workflow.yml
index ce654ee..5f4d01c 100644
--- a/.github/workflows/backwards_compatibility_tests_workflow.yml
+++ b/.github/workflows/backwards_compatibility_tests_workflow.yml
@@ -15,7 +15,7 @@ jobs:
       matrix:
         java: [ 11, 17 ]
         bwc_version : [ "1.0.0", "1.1.0", "1.2.4", "1.3.2", "2.0.0" ]
-        opensearch_version : [ "2.1.0-SNAPSHOT" ]
+        opensearch_version : [ "2.2.0-SNAPSHOT" ]
 
     name: k-NN Restart-Upgrade BWC Tests
     runs-on: ubuntu-latest
@@ -47,7 +47,7 @@ jobs:
       matrix:
         java: [ 11, 17 ]
         bwc_version: [ "1.3.2", "2.0.0" ]
-        opensearch_version: [ "2.1.0-SNAPSHOT" ]
+        opensearch_version: [ "2.2.0-SNAPSHOT" ]
```

**Review by jmazanec15 — APPROVED** [review]

**Comment by bbarani** [comment]
@vamshin  can you please review this PR soon?

**Review by martin-gaievski — APPROVED** [review]

**Pull request merged**
