### PR TITLE
[2.x] Bump version and fix core refactor

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
Bump version and fix core refactor on 2.x branch.
 
 
### Check List
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by junqiu-lei** [comment]
The CI will be expected to fail because of core snapshot 2.10.0 isn't yet out.

**Comment by navneet1v** [comment]
@junqiu-lei can we fix : WhiteSource Security Check?

**Comment by navneet1v** [comment]
> The CI will be expected to fail because of core snapshot 2.10.0 isn't yet out.

are you saying OpenSearch core 2.10 version is not out?

**Comment by junqiu-lei** [comment]
@navneet1v The 2.10.0-SNAPSHOT was just out several hours ago, will check WhiteSource Security error.

**Comment by junqiu-lei** [comment]
WhiteSource Security issue is unrelated to this PR. I raised a new PR for WhiteSource Security fix to main and 2.x https://github.com/opensearch-project/k-NN/pull/1010.

**Review by heemin32 — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]

**Pull request merged**
