### PR TITLE
Upgrade gradle to 8.4

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Upgrade gradle to 8.4 to support JDK-21. Refer to
https://docs.gradle.org/current/userguide/compatibility.html
 
### Issues Resolved
N/A
 
### Check List
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! THanks

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Review by vibrantvarun — APPROVED** [review]

**Review by heemin32 — DISMISSED** [review]

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by navneet1v** [comment]
@jmazanec15 can we check why windows JDK 11 is breaking?

**Comment by jmazanec15** [comment]
@navneet1v Right, I thought windows was broken anyway - didnt realize we fixed it. Let me check what happened.

**Comment by jmazanec15** [comment]
@navneet1v I fixed the windows issue by simplifying the jacoco logic. There were some outdated hacks in there that no longer apply because the OpenSearch TestTask and IntegTestTask extend the gradle Test class now.

**Review by heemin32 — APPROVED** [review]

**Review by ryanbogan — APPROVED** [review]

**Pull request merged**
