### PR TITLE
Add Benchmarking Config for Faiss SQfp16

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Add configuration to run benchmarking test for Faiss SQfp16.

 
### Check List
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ryanbogan — APPROVED** [review]

**Comment by navneet1v** [comment]
@naveentatikonda Lets not add the SQ benchmarks in perf tool and instead put this in OSB. We have migrated our benchmarks to OSB repo. Lets use that repo to add new benchmarks. 

cc: @vamshin

**Comment by naveentatikonda** [comment]
> @naveentatikonda Lets not add the SQ benchmarks in perf tool and instead put this in OSB. We have migrated our benchmarks to OSB repo. Lets use that repo to add new benchmarks.
> 
> cc: @vamshin

Sure I will add it in [OSB-workloads](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/vectorsearch). But, shall we also add it here just in case if we want to run tests using perf-tool. Also, if I'm not wrong as of now the OSB supports vector search with no train procedure only.

**Comment by navneet1v** [comment]
> > @naveentatikonda Lets not add the SQ benchmarks in perf tool and instead put this in OSB. We have migrated our benchmarks to OSB repo. Lets use that repo to add new benchmarks.
> > cc: @vamshin
> 
> Sure I will add it in [OSB-workloads](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/vectorsearch). But, shall we also add it here just in case if we want to run tests using perf-tool. Also, if I'm not wrong as of now the OSB supports vector search with no train procedure only.

Yes it supports only no-train procedures. But SQFp-16 is no train workload right. So we should be able to support it with OSB.

**Comment by navneet1v** [comment]
>  But, shall we also add it here just in case if we want to run tests using perf-tool. 

I would not recommend.

**Comment by naveentatikonda** [comment]
> > > @naveentatikonda Lets not add the SQ benchmarks in perf tool and instead put this in OSB. We have migrated our benchmarks to OSB repo. Lets use that repo to add new benchmarks.
> > > cc: @vamshin
> > 
> > 
> > Sure I will add it in [OSB-workloads](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/vectorsearch). But, shall we also add it here just in case if we want to run tests using perf-tool. Also, if I'm not wrong as of now the OSB supports vector search with no train procedure only.
> 
> Yes it supports only no-train procedures. But SQFp-16 is no train workload right. So we should be able to support it with OSB.

We don't need training for hnsw. But, for ivf we need training. But, that makes sense that we want to migrate to OSB-workloads. Will add it there. Thanks!

**Pull request closed without merging**
