### PR TITLE
Add Integtest.sh for OpenSearch integtest setups

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Add Integtest.sh for OpenSearch integtest setups
This is a file that can be used as an abstraction for integTests to run.
This is better than what ODFE has in which all plugins runs saved in a single yml.
 
### Issues Resolved
https://github.com/opensearch-project/k-NN/issues/45
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jmazanec15** [comment]
Is there a parent issue for this @peterzhuamazon?

**Comment by peterzhuamazon** [comment]
> Is there a parent issue for this @peterzhuamazon?

Here is the issue: https://github.com/opensearch-project/k-NN/issues/45

**Review by jmazanec15 — APPROVED** [review]

**Review by jmazanec15 — APPROVED** [review]

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by peterzhuamazon** [comment]
Please do not merge this I will merged once all the PRs are up.

**Pull request merged**
