### PR TITLE
[Backport 2.x] Introduce a loading layer in NMSLIB. (#2185)

### PR DESCRIPTION
**Pull request by 0ctopus13prime**
Backport https://github.com/opensearch-project/k-NN/commit/7cf45c8cfd4219912d67becb731f8a7af61410c0 from https://github.com/opensearch-project/k-NN/pull/2185

### CODE REVIEW

**Comment by jmazanec15** [comment]
@0ctopus13prime can you fix CI/build?

**Comment by 0ctopus13prime** [comment]
> @0ctopus13prime can you fix CI/build?

Sure, seems like it's a gradle issue from the error message.
All failed CI are failed to resolve a dependency into Apache hc package. 
Could you share how I should deal with this in such case?

```
  in org.opensearch.knn.TestUtils (TestUtils.java:231)
/Users/runner/work/k-NN/k-NN/src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java:9: error: package org.apache.hc.core5.http.io.entity does not exist

import org.apache.hc.core5.http.io.entity.EntityUtils;
```

**Comment by 0ctopus13prime** [comment]
Found the root cause for failing.
In 2.x, we are using `org.apache.http.util.EntityUtils`. Will change import statements in the next commit.

```
-import org.apache.hc.core5.http.io.entity.EntityUtils;
+import org.apache.http.util.EntityUtils;
```

**Review by jmazanec15 — COMMENTED** [review]
Minor comment on CHANGELOG - other than that looks good

**Review by jmazanec15 — APPROVED** [review]
LGTM

**Review by shatejas — APPROVED** [review]

**Pull request merged**
