### PR TITLE
Removes benchmark folder from 2.x branch to resolve CVEs coming from the folder

### PR DESCRIPTION
**Pull request by shatejas**
### Description

Addressing advisories https://advisories.aws.barahmand.com/vulnerabilities/k-NN:%20OpenSearch%20Plugin/origin/main

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VijayanB — APPROVED** [review]
LGTM.

**Review by naveentatikonda — APPROVED** [review]

**Comment by heemin32** [comment]
Are the CVEs coming only from 2.x branch but not main branch? How is that?

**Comment by VijayanB** [comment]
> Are the CVEs coming only from 2.x branch but not main branch? How is that?

@heemin32 You are right. The CVEs are at both main and 2.x. I believe, during release we have strict guideline that no CVEs should be present. Ideally we should fix at main and backport. However, given the issues are with benchmarks/* ( not part of k-nn and they won't be shipped with product ) and imo, we don't need this code at 2.x branch , so it is safe to delete from 2.x branch. We are also working on permanently moving all features from this folder to OSB, so that we can remove from main itself.

**Comment by shatejas** [comment]
> Are the CVEs coming only from 2.x branch but not main branch? How is that?

I did not remove it as perf test are needed during release testing. Can remove it once osb is ready

**Comment by heemin32** [comment]
As long as we are also going to remove benchmark folder from main as well I am fine.

**Comment by navneet1v** [comment]
@shatejas lets port this PR to main branch too, if not already done.

**Comment by naveentatikonda** [comment]
@shatejas Shouldn't we backport this PR to 2.16 branch to fix the CVEs in 2.16 ?

**Pull request merged**
