### PR TITLE
[Backport 2.x] Support script score when doc value is disabled (#1573)

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
backport [1573](https://github.com/opensearch-project/k-NN/pull/1573)
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by navneet1v** [comment]
Will wait for 2.14 increment PR(https://github.com/opensearch-project/k-NN/pull/1574) to be merged before we can merge this PR.

**Review by navneet1v — DISMISSED** [review]

**Comment by navneet1v** [comment]
@jmazanec15 can you look into this PR. Its a backport PR. wasn't merged because 2.x branch was not upgraded to 2.14

**Review by jmazanec15 — APPROVED** [review]

**Comment by navneet1v** [comment]
@bugmakerrrrrr can you raise the PR again by resolving the conflicts.

**Review by navneet1v — APPROVED** [review]

**Comment by navneet1v** [comment]
@jmazanec15 can you approve the code, so that code can be merged.

**Review by jmazanec15 — APPROVED** [review]

**Pull request merged**
