### PR TITLE
Update bwc version after 2.9 release

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
Update versions after 2.9 release: change 2.9.0-SNAPSHOT to 2.9.0, add 2.10.0-SNAPSHOT.
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by navneet1v** [comment]
@junqiu-lei not sure if this change fixes the BWC tests, as I can see the tests in the github actions are failing.

**Comment by junqiu-lei** [comment]
@navneet1v The BWC tests error is unrelated to this PR:
```
> Task :generateTestFixturesEffectiveLombokConfig
/home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java:188: error: cannot find symbol

        XContentType xContentType = XContentType.fromMediaType(response.getEntity().getContentType());
                                                ^
  symbol:   method fromMediaType(String)
  location: class XContentType
> Task :compileTestFixturesJava
/home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java:1277: error: cannot find symbol

        XContentType xContentType = XContentType.fromMediaType(response.getEntity().getContentType());
> Task :compileTestFixturesJava FAILED
                                                ^
  symbol:   method fromMediaType(String)
  location: class XContentType
Note: /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

The error is same as the Geospatial plugin one fixed in the [PR](https://github.com/opensearch-project/geospatial/pull/366). I can help to raise a PR later to fix it.

**Comment by navneet1v** [comment]
> @navneet1v The BWC tests error is unrelated to this PR:
> 
> [Block (21 lines)](#)
> ```
> > Task :generateTestFixturesEffectiveLombokConfig
> /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java:188: error: cannot find symbol
> 
>         XContentType xContentType = XContentType.fromMediaType(response.getEntity().getContentType());
>                                                 ^
>   symbol:   method fromMediaType(String)
>   location: class XContentType
> > Task :compileTestFixturesJava
> /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java:1277: error: cannot find symbol
> 
>         XContentType xContentType = XContentType.fromMediaType(response.getEntity().getContentType());
> > Task :compileTestFixturesJava FAILED
>                                                 ^
>   symbol:   method fromMediaType(String)
>   location: class XContentType
> Note: /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /home/runner/work/k-NN/k-NN/src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 2 errors
> ```
> 
> The error is same as the Geospatial plugin one fixed in the [PR](https://github.com/opensearch-project/geospatial/pull/366). I can help to raise a PR later to fix it.

can we merge in those changes, as this is not very difficult to know why the tests are not passing.

**Comment by navneet1v** [comment]
@junqiu-lei I can still see BWC tests failing. Please check

**Comment by naveentatikonda** [comment]
> There is a new error on the BWC CI:
> 
> ```
> | Output for ./bin/opensearch-plugin:-> Installing file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> > Task :qa:restart-upgrade:testAgainstOldCluster FAILED
> | -> Downloading file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Failed installing file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Rolling back file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Rolled back file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | Exception in thread "main" java.io.FileNotFoundException: /home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip (No such file or directory)
> | 	at java.base/java.io.FileInputStream.open0(Native Method)
> | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
> | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> ```

It is failing because k-NN plugin might not be present in the new artifact, 2.10

**Comment by naveentatikonda** [comment]
> There is a new error on the BWC CI:
> 
> ```
> | Output for ./bin/opensearch-plugin:-> Installing file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> > Task :qa:restart-upgrade:testAgainstOldCluster FAILED
> | -> Downloading file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Failed installing file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Rolling back file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | -> Rolled back file:/home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip
> | Exception in thread "main" java.io.FileNotFoundException: /home/runner/work/k-NN/k-NN/qa/restart-upgrade/build/private/artifact_tmp/opensearch-knn-2.10.0.zip (No such file or directory)
> | 	at java.base/java.io.FileInputStream.open0(Native Method)
> | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
> | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> ```

@junqiu-lei plugins are not added in the [manifest 2.10.0](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.10.0/opensearch-2.10.0.yml). So, the artifact don't have the plugins and the BWC tests are failing

**Comment by naveentatikonda** [comment]
Please fix the DCO check

**Comment by junqiu-lei** [comment]
Looks like infra team will help to add all components to manifest. cc @prudhvigodithi  https://github.com/opensearch-project/opensearch-build/commit/8fb3588baa74258e90e2ebea7e73f0c6b20a93c1

And also we need merge the 2.x PR BWC bump: https://github.com/opensearch-project/k-NN/pull/979

**Comment by naveentatikonda** [comment]
@junqiu-lei Can you also pls fix the Developer Certificate of Origin Check. I think if we don't fix it now, it will cause the DCO check on future PRs also to fail.

**Comment by junqiu-lei** [comment]
Thanks @naveentatikonda, added DCO

**Review by naveentatikonda — APPROVED** [review]

**Review by heemin32 — APPROVED** [review]

**Comment by junqiu-lei** [comment]
The CI failure is expected to fail as k-NN component still not [manifest 2.10.0](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.10.0/opensearch-2.10.0.yml)

**Comment by junqiu-lei** [comment]
Will manually raise PR to fix the core refactor to 2.x and then merge https://github.com/opensearch-project/k-NN/pull/979

**Pull request merged**
