### PR TITLE
Bump version to 1.3.1

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Bump version to 1.3.1
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/1805
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hi @opensearch-project/k-nn  team, can someone take a look at failing CIs and let me know if anything needs to be changed?
Thanks!

**Comment by naveentatikonda** [comment]
@gaiksaya Can you update this  https://github.com/gaiksaya/k-NN-1/blob/1.3.1/.github/workflows/CI.yml#L38 to '1.3.1'

The  

> Hi @opensearch-project/k-nn team, can someone take a look at failing CIs and let me know if anything needs to be changed? Thanks!

@gaiksaya, I think the issue is with https://github.com/gaiksaya/k-NN-1/blob/1.3.1/.github/workflows/CI.yml#L38, which needs to be updated to 1.3.1. I'm testing it, the github action is running.

I guess it is copying both zip files opensearch-knn-1.3.0.0-SNAPSHOT.zip and opensearch-knn-1.3.1.0-SNAPSHOT.zip from distributions to BWC resources which is causing BWC Tests to fail.

**Comment by jmazanec15** [comment]
@gaiksaya  Could we change CI as @peterzhuamazon did in #334 so that we wont have to update this for every patch?

**Comment by gaiksaya** [comment]
> @gaiksaya Could we change CI as @peterzhuamazon did in #334 so that we wont have to update this for every patch?

Removed. Looks like good approach.
Thanks!

**Review by jmazanec15 — APPROVED** [review]

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Review by martin-gaievski — APPROVED** [review]

**Pull request merged**
