### PR TITLE
Remove min cluster version checks

### PR DESCRIPTION
**Pull request by martin-gaievski**
Signed-off-by: Martin Gaievski <gaievski@amazon.com>

### Description
Need to remove min supported version and related bwc test after merging filtering feature to 2.x (https://github.com/opensearch-project/k-NN/pull/589). 

Initially it wasn't required as filtering feature went to main (3.0.0) and 2.x (2.4) didn't have it. Only after feature got backported to 2.x we can remove the version check as it's only purpose is for bwc. Bwc test is not required as all versions that we support for rolling upgrade have filtering feature (they are 2.4+ and any of 3.x in future). 
This PR will not be backported to 2.x
 
### Issues Resolved
https://github.com/opensearch-project/k-NN/issues/376
 
### Check List
- [X] All tests pass
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
Leaving it as a draft for now, there are some problems with building snapshot artifact for 2.4.0, and the latest one that is available doesn't have filtering feature and failing BWC for 2.4.0

**Review by vamshin — DISMISSED** [review]

**Review by jmazanec15 — APPROVED** [review]

**Comment by navneet1v** [comment]
The description explain the min version check, but can you explain why we are removing BWC test?

**Comment by heemin32** [comment]
I think we still need bwc test.

**Comment by navneet1v** [comment]
Approving the PR. As this change is not going to be backported to 2.x branch, and our rolling upgrade test will pick latest version from 2.x which is 2.4 and upgrade to main version(3.0) both of them have filtering support.

**Review by navneet1v — DISMISSED** [review]

**Comment by heemin32** [comment]
> Approving the PR. As this change is not going to be backported to 2.x branch, and our rolling upgrade test will pick latest version from 2.x which is 2.4 and upgrade to main version(3.0) both of them have filtering support.

Shouldn't we made a change in the test to pick <2.4 version for the test?

**Comment by martin-gaievski** [comment]
> I think we still need bwc test.

I doubt we do. We had created [BWC in 2.x](https://github.com/opensearch-project/k-NN/blob/2.x/qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java), for main (3.0.0) is isn't required as the only version supported by rolling upgrade 2.4 and main both have filtering feature. 
I'm not doing backport for this PR so bwc test in 2.x remains unchanged

**Comment by heemin32** [comment]
> > I think we still need bwc test.
> 
> I doubt we do. We had created [BWC in 2.x](https://github.com/opensearch-project/k-NN/blob/2.x/qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java), for main (3.0.0) it isn't required as the only version supported by rolling upgrade is 2.4. Both 2.4 and main have filtering feature. I'm not doing backport for this PR so bwc test in 2.x remains unchanged

We can remove min version check entirely then.

**Comment by martin-gaievski** [comment]
Discussed offline, we can remove check for min cluster version as it was only required for bwc. 

> > > I think we still need bwc test.
> > 
> > 
> > I doubt we do. We had created [BWC in 2.x](https://github.com/opensearch-project/k-NN/blob/2.x/qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java), for main (3.0.0) it isn't required as the only version supported by rolling upgrade is 2.4. Both 2.4 and main have filtering feature. I'm not doing backport for this PR so bwc test in 2.x remains unchanged
> 
> We can remove min version check entirely then.

Good point, it's not required now after we have it in 2.x. I'll remove related code in next commit

**Review by heemin32 — APPROVED** [review]
LGTM. Thanks!

**Comment by heemin32** [comment]
Please update the issue description as well.

**Review by jmazanec15 — APPROVED** [review]

**Pull request merged**
