### PR TITLE
Bump OS version to 2.2.0

### PR DESCRIPTION
**Pull request by junqiu-lei**
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

### Description
Upgrade OpenSearch version to 2.2.0
 
### Issues Resolved
https://github.com/opensearch-project/k-NN/issues/467
 
### Check List
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by naveentatikonda** [comment]
@junqiu-lei BWC Test is failing because we need to update [this](https://github.com/opensearch-project/k-NN/blob/main/qa/restart-upgrade/build.gradle#L97) condition to also include 2.1

**Comment by naveentatikonda** [comment]
@jmazanec15 Should we remove this test "[TestEmptyParametersOnUpgrade](https://github.com/opensearch-project/k-NN/blob/main/qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java#L122)" as we are not supporting it either in 1.x or 2.x version ?

**Review by martin-gaievski — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@junqiu-lei Shall we also update default BWC version in gradle.properties file ?

**Comment by junqiu-lei** [comment]
> @junqiu-lei Shall we also update default BWC version in gradle.properties file to 1.3.4?

Will create a new PR to update the `systemProp.bwc.version` to 1.3.4

**Review by naveentatikonda — APPROVED** [review]

**Comment by jmazanec15** [comment]
> @jmazanec15 Should we remove this test "[TestEmptyParametersOnUpgrade](https://github.com/opensearch-project/k-NN/blob/main/qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java#L122)" as we are not supporting it either in 1.x or 2.x version ?

No we need to keep this in as long as we support upgrade from 1.0 or 1.1. Related: #353

**Pull request merged**
