### PR TITLE
Fix equals and hashCode methods for KNNQuery and KNNQueryBuilder

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
The `equals` and `hashCode` implementations of `KNNQuery` and `KNNQueryBuilder` are missing some fields (`indexName` and `filterQuery` for `KNNQuery`, `filter` and `ignoreUnmapped` for `KNNQueryBuilder`) and are not using the correct array comparison/hash method. 

The error in the relevant unit test is as follows:
```
java.lang.AssertionError: expected: org.opensearch.knn.index.query.KNNQueryBuilder<{
  "knn" : {
    "myvector" : {
      "vector" : [
        1.0,
        2.0,
        3.0,
        4.0
      ],
      "k" : 1,
      "filter" : {
        "term" : {
          "field" : {
            "value" : "value",
            "boost" : 1.0
          }
        }
      },
      "boost" : 1.0
    }
  }
}> but was: org.opensearch.knn.index.query.KNNQueryBuilder<{
  "knn" : {
    "myvector" : {
      "vector" : [
        1.0,
        2.0,
        3.0,
        4.0
      ],
      "k" : 1,
      "filter" : {
        "term" : {
          "field" : {
            "value" : "value",
            "boost" : 1.0
          }
        }
      },
      "boost" : 1.0
    }
  }
}>
	at __randomizedtesting.SeedInfo.seed([9EA5DFBEA12B6A22:F50BAC6E9E6B27AA]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.knn.index.query.KNNQueryBuilderTests.testFromXContent_WithFilter(KNNQueryBuilderTests.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [~] New functionality includes testing.
  - [x] All tests pass
- [~] New functionality has been documented.
  - [~] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
@bugmakerrrrrr thank you for your contribution.

I do have couple of asks:
 - can you please list in PR description what exact fields were added to `equals` and `hashCode` comparing to existing implementation
 - please confirm that the unit tests [KNNQueryBuilderTests.java](https://github.com/opensearch-project/k-NN/pull/1397/files#diff-9e17e9905b7aa43194574d8dfa3447e614a429d6f1d0088ed56d32bdf20a16a4) would fail without your additions to KNNQuery and KNNQueryBuilder

**Comment by bugmakerrrrrr** [comment]
> Also, did you run into a bug for this when running OpenSearch?

No, I just find this bug when I read the code.

**Comment by martin-gaievski** [comment]
You don't need to specify prefix `[Bug] `, we use github labels attached to PR and categories in CHANGELOG file for this. I've corrected PR description, can you please make corresponding change to CHANGELOG

**Review by jmazanec15 — APPROVED** [review]
LGTM

**Review by martin-gaievski — DISMISSED** [review]

**Review by jmazanec15 — APPROVED** [review]

**Review by martin-gaievski — APPROVED** [review]

**Pull request merged**
